project:
  type: book

book:
  title: "Python Programming II for Data Analysis"
  author: "Alex Chisholm"
  date: last-modified
  chapters:
    - index.qmd
    - part: "Python Fundamentals"
      chapters:
      - python-fundamentals/basics.qmd
    - part: "EDA with Pandas"
      chapters:
      - pandas/project-setup.qmd
      - pandas/dataframe.qmd
      - pandas/one-variable-analysis.qmd
      - pandas/multiple-variable-analysis.qmd
      - pandas/data-cleaning.qmd
      - pandas/merging-data.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    toc: true
    toc-depth: 4
    toc-expand: 2
    smooth-scroll: true

